# Question 1

In [59]:
# array
u = rand (3 ,1) # vertical
v = rand (3 ,1)
t = u'*v

println (size(t)) # 1 by 1
println (ndims(t)) # 2 dimensions


(3,1)
(1,1)
2


In [62]:
# vector
x = rand (3) # vertical
y = rand (3)
t = x' *y
println('x', x) # with commas
println (size(t)) # (1, )
println (ndims(t)) # 1 dimensional



x[0.11043002241685151,0.656230953030251,0.6412206388736643]
[0.11043002241685151 0.656230953030251 0.6412206388736643]
[0.11043002241685151 0.656230953030251 0.6412206388736643]
(1,)
1


In [18]:
#d = dot(u,v) # can't execute
s = sum(u.*v)

0.25772894219550735

In [29]:
d = dot(x,y) 
println(d)
s = sum(x.*y)
print(s)

1.1243686622558366
1.1243686622558366

In [68]:
srand(2)
A = rand(5,5)
column = A[:,1]
size(column) # 5 rows, vector
row = A[1,:]
size (row)# 1 by 5 matrix

(1,5)

In [87]:
# Method 1: change column vector to horizontal matrix
t = reshape(column, 1, 5)
println(t)
println (row)
sum(t.*row);

[0.36679641243992434 0.5238785747844117 0.21025643065331256 0.8193381354589955 0.5013711485175227]
[0.36679641243992434 0.559355291249767 0.14383562117576143 0.24225804087259806 0.13843052661356103]


0.7257125488926944

In [93]:
# Method 2: convert row vector to column matrix
a = Float64 []
for i in row[1,1:5]
    push!(a,i); 
end
println (a) # vertical array

b = reshape (a,5,1) # vertical matrix
sum (column.*b) # both are vertical

[0.36679641243992434,0.559355291249767,0.14383562117576143,0.24225804087259806,0.13843052661356103]


0.7257125488926944